POST http://localhost:8000/api/v1/institute
Content-Type: application/json
x-institute-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3Rpb24iOiJjcmVhdGVfYWN0aW9uIiwiaWF0IjoxNzU5MTI5MTA0LCJleHAiOjE3NTkxMjk0MDR9.Jt6wSZZSE2gvVc5PVvLIkppyC_RMfAVPkgtK7Gd30z8

{
  "name": "Arpan's College",
  "email": "admin@intelbuzz.in",
  "password": "demo"
}

###

GET http://localhost:8000/foo

###
POST http://localhost:8000/ins
Content-Type: application/json

{
  "data":"this is some data"
}