POST http://localhost:8000/api/v1/institute
Content-Type: application/json
x-institute-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3Rpb24iOiJjcmVhdGVfYWN0aW9uIiwiaWF0IjoxNzU4ODg5MDMyLCJleHAiOjE3NTg4ODkzMzJ9.M-38aZKOUwcD6IKHRaZsel0gY7vYiI9-4JG_2rJniLo

{
  "name": "XYZ College",
  "email": "adityapaluskar@gmail.com",
  "password": "Gamer"
}

###

GET http://localhost:8000/foo

###
POST http://localhost:8000/ins
Content-Type: application/json

{
  "data":"this is some data"
}