version: '1.0'
services:
  nextjs-app:
  image: nextjs-app
  container_name: nextjs-app
  build:
    context: .
  ports:
    -'${APP_PORT}:${APP_PORT}'
  volumes:
    -./app:/app
    - node_modules:/app/node_modules
    - buil:/app/.next
  env_file:
    - .env

volumes:
  node_modules
  build